# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: agg-8xtp2
  namespace: inference-engine
spec:
  backendFramework: vllm
  pvcs:
  - create: false
    name: model-cache-pvc
  - create: true
    name: compilation-cache
    size: 50Gi
    storageClass: local-path
    volumeAccessMode: ReadWriteOnce
  services:
    Frontend:
      componentType: frontend
      envs:
        - name: HF_HOME
          value: /home/.cache/huggingface
      extraPodSpec:
        nodeSelector:
          inference-node: debian
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.9.1
          workingDir: /workspace
          command:
            - python3
            - -m
            - dynamo.frontend
          args:
            - --router-reset-states
      replicas: 1
      resources:
        requests:
          cpu: "8"
        limits:
          cpu: "8"
      subComponentType: null
    VllmDecodeWorker:
      componentType: worker
      envFromSecret: api-keys-secret
      envs:
        - name: MODEL_DOWNLOAD_NAME
          valueFrom:
            configMapKeyRef:
              name: inference-engine-config
              key: MODEL_DOWNLOAD_NAME
        - name: MODEL_CONTEXT_LENGTH
          valueFrom:
            configMapKeyRef:
              name: inference-engine-config
              key: MODEL_CONTEXT_LENGTH
      volumeMounts:
      - name: model-cache-pvc
        mountPoint: /home/dynamo/.cache/huggingface
      - name: compilation-cache
        mountPoint: /home/dynamo/.cache/vllm
        useAsCompilationCache: true
      extraPodSpec:
        nodeSelector:
          inference-node: pop-os
        mainContainer:
          args:
            - --model
            - $(MODEL_DOWNLOAD_NAME)
            - --tensor-parallel-size
            - '1'
            - --disable-log-requests
            - --gpu-memory-utilization
            - '0.85'
            - --async-scheduling
            - --block-size
            - '64'
            - --hf-overrides
            - --max-model-len
            - $(MODEL_CONTEXT_LENGTH)
          command:
            - python3
            - -m
            - dynamo.vllm
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.9.1
          env:
            - name: DYN_HEALTH_CHECK_ENABLED
              value: "false"
            - name: HF_HOME
              value: /home/dynamo/.cache/huggingface
          workingDir: /workspace
      replicas: 1
      resources:
        limits:
          gpu: '1'
        requests:
          gpu: '1'
      subComponentType: decode
