# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: agg-8xtp2
  namespace: inference-engine
spec:
  backendFramework: vllm
  pvcs:
  - create: false
    name: model-cache-pvc
  - create: true
    name: compilation-cache
    size: 50Gi
    storageClass: local-path
    volumeAccessMode: ReadWriteOnce
  services:
    Frontend:
      componentType: frontend
      envs:
        - name: HF_HOME
          value: /home/.cache/huggingface
      extraPodSpec:
        nodeSelector:
          inference-node: debian
        mainContainer:
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.9.1
          workingDir: /workspace
          command:
            - python3
            - -m
            - dynamo.frontend
          args:
            - --router-reset-states
      replicas: 1
      resources:
        requests:
          cpu: "2"
        limits:
          cpu: "4"
      subComponentType: "null"
    VllmDecodeWorker:
      componentType: worker
      envFromSecret: api-keys-secret
      envs:
        - name: MODEL_SNAPSHOT_PATH
          valueFrom:
            configMapKeyRef:
              name: inference-engine-config
              key: MODEL_SNAPSHOT_PATH
        - name: MODEL_CONTEXT_LENGTH
          valueFrom:
            configMapKeyRef:
              name: inference-engine-config
              key: MODEL_CONTEXT_LENGTH
        - name: MODEL_DOWNLOAD_FILE
          valueFrom:
            configMapKeyRef:
              name: inference-engine-config
              key: MODEL_DOWNLOAD_FILE
      volumeMounts:
      - name: model-cache-pvc
        mountPoint: /home/.cache/huggingface
      - name: compilation-cache
        mountPoint: /home/.cache/vllm
        useAsCompilationCache: true
      extraPodSpec:
        runtimeClassName: nvidia
        nodeSelector:
          inference-node: pop-os
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
        mainContainer:
          args:
            - --model
            - $(MODEL_SNAPSHOT_PATH)/$(MODEL_DOWNLOAD_FILE)
            - --tensor-parallel-size
            - '1'
            - --disable-log-requests
            - --gpu-memory-utilization
            - '0.90'
            - --async-scheduling
            - --block-size
            - '16'
            - --max-model-len
            - $(MODEL_CONTEXT_LENGTH)
            - --load-format
            - gguf
            - --dtype
            - float16
            - --tokenizer
            - Qwen/Qwen3-30B-A3B
            - --kv-offloading-size
            - $(KV_OFFLOADING_SIZE)
            - --kv-offloading-backend
            - native
          command:
            - python3
            - -m
            - dynamo.vllm
          image: nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.9.1
          env:
            - name: DYN_HEALTH_CHECK_ENABLED
              value: "false"
            - name: HF_HOME
              value: /home/.cache/huggingface
            - name: KV_OFFLOADING_SIZE
              valueFrom:
                configMapKeyRef:
                  name: inference-engine-config
                  key: KV_OFFLOADING_SIZE
          workingDir: /workspace
      replicas: 1
      resources:
        limits:
          gpu: '1'
          memory: 8Gi
        requests:
          gpu: '1'
          memory: 6Gi
      livenessProbe:
        httpGet:
          path: /live
          port: 9090
        initialDelaySeconds: 600
        periodSeconds: 30
        failureThreshold: 10
      subComponentType: decode
