apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-engine-config
  namespace: inference-engine
data:
  INFERENCE_PORT: "8000"
  # SYSTEM_PROMPT: "You are a helpful assistant. Follow safety and policy instructions."
  MIDDLEWARE_UPSTREAM_BASE_URL: "http://llm-service.inference-engine.svc.cluster.local"
  MODEL_DOWNLOAD_NAME: "unsloth/Qwen3-30B-A3B-GGUF"
  MODEL_DOWNLOAD_FILE: "Qwen3-30B-A3B-UD-Q2_K_XL.gguf"
  MODEL_DOWNLOAD_REVISION: "main"
  MODEL_SNAPSHOT_PATH: "/home/.cache/huggingface/hub/models--unsloth--Qwen3-30B-A3B-GGUF/snapshots/d5b1d57bd0b504ac62ae6c725904e96ef228dc74"
  HF_HOME: "/home/.cache/huggingface"
  HF_HUB_ENABLE_HF_TRANSFER: "1"
  MODEL_CONTEXT_LENGTH: "15728"
  KV_OFFLOADING_SIZE: "6"
