apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-engine-config
  namespace: inference-engine
data:
  INFERENCE_PORT: "8000"
  # SYSTEM_PROMPT: "You are a helpful assistant. Follow safety and policy instructions."
  MIDDLEWARE_UPSTREAM_BASE_URL: "http://llm-service.inference-engine.svc.cluster.local"
  MODEL_DOWNLOAD_NAME: "unsloth/gpt-oss-20b-GGUF"
  MODEL_DOWNLOAD_FILE: "gpt-oss-20b.Q5_K_M.gguf"
  MODEL_DOWNLOAD_REVISION: "main"
  HF_HOME: "/home/.cache/huggingface"
  HF_HUB_ENABLE_HF_TRANSFER: "1"
  MODEL_CONTEXT_LENGTH: "32768"
