apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-ingress
  namespace: inference-engine
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - chat.alifaiman.cloud
    secretName: llm-tls
  rules:
  - host: chat.alifaiman.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: middleware-service
            port:
              number: 80
