loki:
  auth_enabled: false
  useTestSchema: true
  commonConfig:
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  ingester:
    lifecycler:
      ring:
        replication_factor: 1
  memberlist:
    join_members: []
  storage:
    type: filesystem
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp2

deploymentMode: SingleBinary

lokiCanary:
  enabled: false

test:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

gateway:
  enabled: true

monitoring:
  serviceMonitor:
    enabled: true

write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
