apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-head-metrics
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - inference-engine
  selector:
    matchLabels:
      app: ray-head-metrics
  endpoints:
  - port: dashboard
    path: /metrics
    interval: 30s
