apiVersion: v1
kind: Service
metadata:
  name: ray-vllm-head
  namespace: inference-engine
  labels:
    app: ray-vllm-head
spec:
  selector:
    ray.io/node-type: head
  ports:
  - name: serve
    port: 8000
    targetPort: 8000
